name: Build generic-debian
on:
  push:
    branches:
      - main
    paths:
      - generic/debian/*
      - generic/entrypoint.sh
      - .github/workflows/generic-debian.yml
  schedule:
    - cron: '0 2 * * 1'  # Weekly rebuild for security updates

jobs:
  push:
    name: "generic-debian"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v5
        with:
          context: ./generic
          file: ./generic/debian/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cubexcloudhosting/images:generic-debian
          cache-from: type=gha
          cache-to: type=gha,mode=max
